### ISSUE TITLE
Twitter Stats not being repoted

### ISSUE THREAD

**Issue by linuxlite** [juanv911/SocialCounters#3]
I have all of the stats working except for Twitter, see here - https://www.linuxliteos.com/index2.html

I changed the path in the js file to: url: '../twitter/index.php',

I've created my app in Twitter Dev. When I click on the 'Test OAuth' button for my app in Twitter Dev, I get an error page 'Sorry, that page doesn’t exist!' Could this be the reason I'm not getting the Twitter stats? How can I fix this?

Thank you.

**Comment by DannyCare** [comment]
Looks like you fixed it, as I can see the twitter followers now! Can you share your fix?

**Comment by linuxlite** [comment]
Can you provide a screenshot please, because it's still not showing here.

![screenshot_2017-05-14_20-16-02](https://cloud.githubusercontent.com/assets/5382578/26032225/3c88a37a-38e2-11e7-82c1-c10d41945bab.png)

**Comment by DannyCare** [comment]
<img width="900" alt="screen shot 2017-05-14 at 09 28 17" src="https://cloud.githubusercontent.com/assets/8669469/26032297/c589df0a-3887-11e7-9760-b9765e1c1a3c.png">

Works whether I'm logged in or out of a Twitter account and also works on Safari.

**Comment by linuxlite** [comment]
Well that's interesting, thank you. I've tried different computers, different OS's cleared browser cache, the works. No change. Thanks for the screenshot though. I'll try from another location.

**Comment by DannyCare** [comment]
Definitely, try a VPN, maybe with 4G on your phone. It could be an issue with your router or ISP :)

Bizarrely enough, when I checked out the Codepen the other day it looked as though the Twitter wasn't working for me, pretty much the exact thing that's happening to you right now. Could be Twitter's API? Not sure.

**Comment by linuxlite** [comment]
It's now working. No idea why, no change to the code.
